project:
  type: website
  output-dir: docs

website:
  title: "SO - Fall 2025"
  description: "Course materials for SO - Fall 2025"
  site-url: "https://os-gei-udl-2526-105012.github.io/course/"
  repo-url: https://github.com/os-gei-udl-2526-105012/course

  sidebar:
    logo: /figures/logo.png
    logo-width: 75px
    logo-height: 75px
    logo-alt: "SO Logo"
    pinned: true
    tools:
    - icon: house
      href: "index.html"
      text: "Home"
    - icon: github
      href: "https://github.com/os-gei-udl-2526-105012/course"
      text: "GitHub organization"
    - icon: person-fill
      text: "Sakai"
      href: "https://cv.udl.cat/"

    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - section: Informació del curs
        contents:
          - href: ./course-information/schedule.html
            text: Planificació
      - section: Diapositives
        contents:
          - href: ./slides/01-introduction.qmd
            text: Unitat 01 ·Introducció als sistemes operatius
          - href: ./slides/01-c.qmd
            text: Unitat 01 ·Introducció a la programació de Sistema (I) (C)
      - section: Apunts
        contents:
          - href: ./notes/01-introduction.qmd
            text: Unitat 01 ·Introducció als sistemes operatius
      - section: Laboratoris
        contents:
          - section: Unitat 01
            contents:
              - href: ./labs/01-lab-introduction.qmd
                text: Laboratori · Virtualització i Control de Versions 
              - href: ./labs/01-introduction/lab01.qmd
                text: Laboratori 1 · Instal·lació i configuració d'un entorn Linux
              - href: ./labs/01-introduction/lab02.qmd
                text: Laboratori 2 · Configurant el meu entorn de desenvolupament amb VSCode
              - href: ./labs/01-introduction/lab03.qmd
                text: Laboratori 3 · Hola món en C a Debian
              - href: ./labs/01-introduction/lab04.qmd
                text: Laboratori 4 · Configurant Git a la màquina virtual
              - href: ./labs/01-introduction/lab05.qmd
                text: Laboratori 5 · Calculadora col·laborativa amb C
      - section: Activitats
        contents:
          - section: Unitat 01
            contents:
              - href: ./activities/unit00/01-debianbin.qmd
                text: RMSF · Implementant una paperera de reciclatge a Linux
              - href: ./activities/unit00/02-ex01-c.qmd
                text: Exercicis amb C - Pokemon· 


  
format:
  html:
    toc: true
    theme: 
      - cosmo
      - brand

